# Generated by Django 3.2.9 on 2021-11-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTorqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPlan', models.DateTimeField()),
                ('nodo', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('proyecto', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tuercas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('medida', models.CharField(max_length=10)),
                ('acabado', models.CharField(max_length=15)),
            ],
        ),
    ]
