# Generated by Django 3.2.9 on 2021-12-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanTorqueo',
        ),
        migrations.AddField(
            model_name='tuercas',
            name='date_torq',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tuercas',
            name='estado',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tuercas',
            name='nodo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tuercas',
            name='proyecto',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
