# Generated by Django 3.2.9 on 2021-12-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211215_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuercas',
            name='ID',
            field=models.IntegerField(null=True),
        ),
    ]
