# Generated by Django 3.2.9 on 2021-12-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tuercas_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip_codigo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip_estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perno',
            fields=[
                ('fecha_perno', models.CharField(max_length=50)),
                ('tiempo', models.CharField(max_length=50)),
                ('id_perno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('estado_perno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Union',
            fields=[
                ('fecha_union', models.DateField()),
                ('hora_union', models.CharField(max_length=50)),
                ('id_union', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('referencia', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Tuercas',
        ),
        migrations.AddField(
            model_name='perno',
            name='union_perno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.union'),
        ),
        migrations.AddField(
            model_name='estado',
            name='salida_perno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.perno'),
        ),
        migrations.AddField(
            model_name='estado',
            name='salida_union',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.union'),
        ),
        migrations.AddField(
            model_name='codigosalida',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado'),
        ),
    ]
